import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
import * as path from 'path'

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

const supabase = createClient(supabaseUrl, supabaseServiceKey)

interface PrecedentSeed {
  case_name: string
  citation: string | null
  citation_type: string | null
  court: string
  court_code: string
  year: number | null
  appellant: string | null
  respondent: string | null
  judge_names: string[]
  bench_type: string | null
  law_category: string
  law_subcategory: string | null
  statutes: string[]
  keywords: string[]
  headnotes: string
  holding: string
  outcome: string | null
  is_landmark: boolean
  landmark_reason: string | null
  source: string
}

const precedents: PrecedentSeed[] = [
  // ============================================================
  // CONSTITUTIONAL CASES (6)
  // ============================================================
  {
    case_name: 'Asma Jilani v Government of Punjab',
    citation: 'PLD 1972 SC 139',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 1972,
    appellant: 'Asma Jilani',
    respondent: 'Government of Punjab',
    judge_names: ['Hamoodur Rahman CJ', 'Yaqub Ali J', 'Sajjad Ahmad J', 'Waheeduddin Ahmad J', 'Muhammad Yaqub Ali J'],
    bench_type: 'Full Bench',
    law_category: 'Constitutional',
    law_subcategory: 'Fundamental Rights / Habeas Corpus',
    statutes: ['Constitution of Pakistan 1962', 'West Pakistan Maintenance of Public Order Ordinance'],
    keywords: ['habeas corpus', 'fundamental rights', 'detention', 'rule of law', 'constitutional supremacy', 'martial law validity'],
    headnotes: 'This landmark case arose from the detention of Malik Ghulam Jilani under the West Pakistan Maintenance of Public Order Ordinance during the Yahya Khan martial law regime. The petitioner challenged the legality of her father\'s detention and the validity of the martial law regime itself. The Supreme Court was asked to determine whether courts retained jurisdiction to examine the legality of detentions during martial law. The case raised fundamental questions about the relationship between constitutional governance and extra-constitutional regimes.',
    holding: 'The Supreme Court held that Yahya Khan\'s assumption of power was illegal and unconstitutional, as there is no legal justification for the abrogation of a constitution. Courts cannot recognize the validity of actions taken under an illegal regime. The doctrine of necessity cannot be stretched to validate illegal seizure of power. Fundamental rights are inviolable and courts retain jurisdiction to protect them even during martial law.',
    outcome: 'Petition allowed; detention declared illegal',
    is_landmark: true,
    landmark_reason: 'First Supreme Court judgment to declare a military government illegal; established that courts cannot validate unconstitutional seizure of power; foundational precedent for constitutional supremacy in Pakistan',
    source: 'Manual',
  },
  {
    case_name: 'Begum Nusrat Bhutto v Chief of Army Staff',
    citation: 'PLD 1977 SC 657',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 1977,
    appellant: 'Begum Nusrat Bhutto',
    respondent: 'Chief of Army Staff and Federation of Pakistan',
    judge_names: ['Anwarul Haq CJ', 'Muhammad Akram J', 'Dorab Patel J', 'Muhammad Haleem J', 'Qaiser Khan J'],
    bench_type: 'Full Bench',
    law_category: 'Constitutional',
    law_subcategory: 'Doctrine of Necessity / Martial Law',
    statutes: ['Constitution of Pakistan 1973', 'Proclamation of Martial Law 1977'],
    keywords: ['doctrine of necessity', 'martial law', 'constitutional validity', 'elections', 'General Zia ul Haq', 'PCO'],
    headnotes: 'Following General Zia ul Haq\'s coup against Prime Minister Zulfikar Ali Bhutto in July 1977, Begum Nusrat Bhutto challenged the validity of the military takeover in the Supreme Court. The case tested whether the doctrine of state necessity could justify an extra-constitutional intervention. The court examined the doctrine as developed in Pakistani, English, and comparative jurisprudence. This case became a defining moment in Pakistan\'s constitutional history.',
    holding: 'The Supreme Court validated General Zia\'s military takeover on the basis of the doctrine of state necessity, holding that where constitutional breakdown occurs and the legal order is on the verge of collapse, the courts may recognize a de facto government. However, the court imposed conditions: the regime must restore the constitution as soon as possible, hold elections, and not deviate from the constitution more than necessary. The court retained supervisory jurisdiction.',
    outcome: 'Petition dismissed; martial law validated subject to conditions',
    is_landmark: true,
    landmark_reason: 'Applied the doctrine of state necessity to validate military rule; set conditions for such validation; later criticized as judicial over-reach; shaped constitutional jurisprudence for decades',
    source: 'Manual',
  },
  {
    case_name: 'Zafar Ali Shah v General Pervez Musharraf',
    citation: 'PLD 2000 SC 869',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 2000,
    appellant: 'Syed Zafar Ali Shah',
    respondent: 'General Pervez Musharraf (Chief Executive) and others',
    judge_names: ['Irshad Hassan Khan CJ', 'Rana Bhagwandas J', 'Nazim Hussain Siddiqui J', 'Sh. Riaz Ahmad J', 'Munir A. Sheikh J'],
    bench_type: 'Full Court',
    law_category: 'Constitutional',
    law_subcategory: 'Doctrine of Necessity / Military Takeover',
    statutes: ['Constitution of Pakistan 1973', 'Proclamation of Emergency 1999', 'Provisional Constitutional Order 1999'],
    keywords: ['doctrine of necessity', 'coup', 'Musharraf', 'PCO', 'October 1999', 'constitutional validity', 'amendment power'],
    headnotes: 'This case challenged the validity of General Pervez Musharraf\'s military coup of October 12, 1999, which overthrew the elected government of Prime Minister Nawaz Sharif. Multiple petitions were filed challenging the suspension of the constitution and the dismissal of elected assemblies. The court was required to examine whether the doctrine of state necessity could once again be invoked to validate extra-constitutional action. The judgment also addressed the power of a military government to amend the constitution.',
    holding: 'The Supreme Court validated the October 1999 coup on grounds of state necessity, finding that the elected government had brought the country to the brink of destabilization. The court granted Musharraf three years to hold elections and restore democracy. Critically, the court held that the Chief Executive had limited power to amend the constitution, only to the extent necessary to achieve stated goals. The court retained power of judicial review over PCO actions.',
    outcome: 'Coup validated with conditions including three-year timeline for elections',
    is_landmark: true,
    landmark_reason: 'Third major doctrine-of-necessity case; validated military rule with conditions; later used as precedent by Musharraf to amend constitution extensively; significant for constitutional law scholarship',
    source: 'Manual',
  },
  {
    case_name: 'Mian Muhammad Nawaz Sharif v Federation of Pakistan (Panama Case)',
    citation: 'PLD 2017 SC 692',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 2017,
    appellant: 'Imran Ahmad Khan Niazi and others',
    respondent: 'Mian Muhammad Nawaz Sharif and others',
    judge_names: ['Asif Saeed Khan Khosa J', 'Ejaz Afzal Khan J', 'Gulzar Ahmed J', 'Sh. Azmat Saeed J', 'Ijaz ul Ahsan J'],
    bench_type: 'Five-Member Bench',
    law_category: 'Constitutional',
    law_subcategory: 'Accountability / Disqualification of PM',
    statutes: ['Constitution of Pakistan 1973 Art 62 & 63', 'National Accountability Bureau Ordinance 1999', 'Representation of People Act 1976'],
    keywords: ['Panama Papers', 'Nawaz Sharif', 'disqualification', 'Article 62', 'sadiq and ameen', 'offshore accounts', 'accountability', 'JIT'],
    headnotes: 'This historic case arose from the Panama Papers leak revealing offshore assets held by the family of Prime Minister Nawaz Sharif. Opposition parties filed petitions for his disqualification under Articles 62 and 63 of the Constitution for being not "sadiq" (honest) and "ameen" (righteous). The court constituted a Joint Investigation Team (JIT) to probe the allegations. The case raised fundamental questions about parliamentary accountability, judicial review of elected representatives, and the scope of Articles 62-63.',
    holding: 'By a majority of 3-2, the Supreme Court disqualified Nawaz Sharif from holding public office under Article 62(1)(f), holding that he had failed to declare his receivable salary from a UAE company in his nomination papers, making him not sadiq and ameen. The JIT investigation revealed significant financial irregularities. The court held that a Prime Minister can be disqualified mid-term by the Supreme Court under Articles 184(3) and 62-63.',
    outcome: 'Nawaz Sharif disqualified as Prime Minister; NAB references ordered',
    is_landmark: true,
    landmark_reason: 'First disqualification of a sitting Prime Minister by Supreme Court; expansive interpretation of Article 62(1)(f); established Supreme Court jurisdiction under Article 184(3) for elected officials\' accountability; highly controversial and politically significant',
    source: 'Manual',
  },
  {
    case_name: 'Shirin Munir v Government of Punjab',
    citation: 'PLD 1990 SC 295',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 1990,
    appellant: 'Shirin Munir and others',
    respondent: 'Government of Punjab and others',
    judge_names: ['Nasim Hassan Shah CJ', 'Abdul Qadeer Chaudhry J', 'Ajmal Mian J'],
    bench_type: 'Three-Member Bench',
    law_category: 'Constitutional',
    law_subcategory: 'Fundamental Rights / Gender Equality',
    statutes: ['Constitution of Pakistan 1973 Art 25', 'Punjab Medical College Ordinance'],
    keywords: ['gender equality', 'Article 25', 'discrimination', 'merit', 'medical colleges', 'women rights', 'equal protection'],
    headnotes: 'Female medical students challenged the provincial government\'s policy of maintaining separate merit lists for male and female students in medical college admissions, which effectively gave male students an advantage in gaining admission. The petitioners argued this violated the constitutional guarantee of equality before law under Article 25. The case examined whether the gender-segregated admissions policy constituted impermissible discrimination or fell within the protective discrimination exception.',
    holding: 'The Supreme Court held that maintaining separate merit lists for male and female medical students violated Article 25 of the Constitution guaranteeing equality before law. The protective discrimination clause in Article 25(3) does not authorize a government to discriminate against women in access to education. Merit-based admissions must apply equally to all citizens regardless of gender. The policy was struck down as unconstitutional.',
    outcome: 'Petition allowed; separate merit lists struck down',
    is_landmark: true,
    landmark_reason: 'Landmark for gender equality in education; strong interpretation of Article 25; frequently cited in women\'s rights cases; established that protective discrimination cannot be used against women',
    source: 'Manual',
  },
  {
    case_name: 'Reference v Zulfikar Ali Bhutto',
    citation: 'PLD 1979 SC 53',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 1979,
    appellant: 'State / Federation of Pakistan',
    respondent: 'Zulfikar Ali Bhutto',
    judge_names: ['Anwarul Haq CJ', 'Waheeduddin Ahmed J', 'Muhammad Haleem J', 'Nasim Hassan Shah J', 'Karam Elahee Chauhan J'],
    bench_type: 'Full Bench (7 Judges)',
    law_category: 'Criminal',
    law_subcategory: 'Murder / High Treason',
    statutes: ['Pakistan Penal Code 1860 s.302', 'Criminal Procedure Code 1898', 'Evidence Act'],
    keywords: ['murder', 'conspiracy', 'political assassination', 'Bhutto', 'death penalty', 'fair trial', 'circumstantial evidence'],
    headnotes: 'Former Prime Minister Zulfikar Ali Bhutto was tried for conspiracy to murder Ahmad Raza Kasuri, a political opponent. The prosecution alleged that Bhutto had directed the Federal Security Force to assassinate Kasuri but that Kasuri\'s father was killed instead. The case raised profound questions about the fairness of criminal trials involving high political figures during martial law. The evidence was largely circumstantial and the proceedings were controversial.',
    holding: 'By a majority of 4-3, the Supreme Court upheld the conviction and death sentence. The court held that circumstantial evidence, if cogent and consistent, can sustain a murder conviction. The majority found the prosecution\'s evidence credible despite contradictions. The three dissenting judges expressed serious doubt about the adequacy of evidence. Bhutto was hanged on April 4, 1979.',
    outcome: 'Conviction upheld; death sentence executed',
    is_landmark: true,
    landmark_reason: 'Most controversial criminal case in Pakistan\'s history; execution of a former Prime Minister; later questioned by successor courts; raised issues of judicial independence during martial law; subject of ongoing debate',
    source: 'Manual',
  },

  // ============================================================
  // CRIMINAL CASES (6)
  // ============================================================
  {
    case_name: 'Liaquat Hussain v Federation of Pakistan',
    citation: 'PLD 1999 SC 504',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 1999,
    appellant: 'Liaquat Hussain and others',
    respondent: 'Federation of Pakistan',
    judge_names: ['Ajmal Mian CJ', 'Saiduzzaman Siddiqui J', 'Fazal Ilahi Khan J', 'Rana Bhagwandas J', 'Mamoon Kazi J'],
    bench_type: 'Full Court',
    law_category: 'Criminal',
    law_subcategory: 'Military Courts / Anti-Terrorism',
    statutes: ['Anti-Terrorism Act 1997', 'Constitution of Pakistan 1973 Art 175', 'Pakistan Army Act 1952'],
    keywords: ['military courts', 'civilians', 'jurisdiction', 'fair trial', 'Article 175', 'speedy trial courts', 'fundamental rights'],
    headnotes: 'The government established special military courts to try civilians accused of terrorism offenses under the Anti-Terrorism Act 1997. The petitioners challenged the jurisdiction of military courts to try civilians, arguing it violated the constitutional guarantee of trial by civilian courts and the right to a fair trial. The case raised the fundamental question of whether civilians can constitutionally be tried by military tribunals in Pakistan.',
    holding: 'The Supreme Court held that military courts cannot try civilians as this violates Article 175 of the Constitution which establishes an integrated judicial system. The right to be tried by a competent civil court is a fundamental right. The Anti-Terrorism Act provisions allowing military courts to try civilians were declared unconstitutional. Civilians must be tried only by courts established under Article 175.',
    outcome: 'Military courts for civilians declared unconstitutional',
    is_landmark: true,
    landmark_reason: 'Definitively established that civilians cannot be tried by military courts; vital for rule of law; repeatedly cited whenever military court jurisdiction is challenged; shaped anti-terrorism legislation',
    source: 'Manual',
  },
  {
    case_name: 'Muhammad Mansha v The State',
    citation: 'PLD 2018 SC 395',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 2018,
    appellant: 'Muhammad Mansha',
    respondent: 'The State',
    judge_names: ['Asif Saeed Khan Khosa J', 'Mushir Alam J'],
    bench_type: 'Two-Member Bench',
    law_category: 'Criminal',
    law_subcategory: 'Murder / Benefit of Doubt',
    statutes: ['Pakistan Penal Code 1860 s.302', 'Qanun-e-Shahadat Order 1984 Art 117'],
    keywords: ['benefit of doubt', 'murder', 'circumstantial evidence', 'acquittal', 'reasonable doubt', 'prosecution burden'],
    headnotes: 'The appellant was convicted of murder and sentenced to death by the trial court, which was upheld by the High Court. The Supreme Court examined the quality of evidence relied upon by the lower courts. The case raised the classic question of the standard of proof in criminal cases and the entitlement of an accused person to the benefit of reasonable doubt when the prosecution evidence is inconsistent or unreliable.',
    holding: 'The Supreme Court held that the prosecution bears the burden of proving guilt beyond reasonable doubt. Even a single reasonable doubt in the prosecution\'s case is sufficient to acquit the accused. The court reiterated that benefit of doubt is not a concession or a privilege but a right of the accused. Where two interpretations are possible from the evidence, the one favorable to the accused must be adopted. Conviction set aside.',
    outcome: 'Conviction set aside; accused acquitted',
    is_landmark: false,
    landmark_reason: null,
    source: 'Manual',
  },
  {
    case_name: 'Muhammad Akram v The State',
    citation: 'PLD 2009 SC 230',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 2009,
    appellant: 'Muhammad Akram',
    respondent: 'The State',
    judge_names: ['Iftikhar Muhammad Chaudhry CJ', 'Mian Shakirullah Jan J'],
    bench_type: 'Two-Member Bench',
    law_category: 'Criminal',
    law_subcategory: 'Rape / Zina / Evidence',
    statutes: ['Zina (Enforcement of Hudood) Ordinance 1979', 'Qanun-e-Shahadat Order 1984', 'Pakistan Penal Code 1860 s.375-376'],
    keywords: ['rape', 'zina', 'evidence', 'consent', 'victim testimony', 'corroboration', 'women protection'],
    headnotes: 'This case involved charges under the Hudood Ordinances relating to zina bil-jabr (rape). The court was called upon to examine the evidentiary requirements for establishing rape under both Hudood and Tazir provisions. The case addressed the controversial issue of whether the victim\'s uncorroborated testimony could sustain a conviction and the evidentiary standards applicable after the Women Protection Act 2006.',
    holding: 'The Supreme Court held that the testimony of a rape victim is entitled to full credibility and does not require corroboration as a rule of law. The victim of sexual assault cannot be treated as an accomplice. The evidence of the victim alone, if found reliable and consistent, is sufficient for conviction. The court emphasized that requiring corroboration in rape cases adds to the trauma of victims and is contrary to principles of justice.',
    outcome: 'Conviction maintained on modified grounds; victim testimony upheld',
    is_landmark: false,
    landmark_reason: null,
    source: 'Manual',
  },
  {
    case_name: 'Control of Narcotic Substances — Muhammad Aslam v The State',
    citation: 'PLD 2011 SC 350',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 2011,
    appellant: 'Muhammad Aslam',
    respondent: 'The State',
    judge_names: ['Tassaduq Hussain Jillani J', 'Muhammad Sair Ali J'],
    bench_type: 'Two-Member Bench',
    law_category: 'Criminal',
    law_subcategory: 'Drug Trafficking / CNSA',
    statutes: ['Control of Narcotic Substances Act 1997 s.9', 'Pakistan Penal Code 1860', 'Criminal Procedure Code 1898'],
    keywords: ['narcotics', 'drugs', 'trafficking', 'CNSA', 'recovery', 'conscious possession', 'life imprisonment', 'death penalty'],
    headnotes: 'The appellant was convicted under Section 9(c) of the Control of Narcotic Substances Act 1997 for possessing a large quantity of heroin and sentenced to death. The court examined the legal requirements for establishing conscious possession of narcotics, the chain of custody of evidence, and the proportionality of the death penalty for drug trafficking offenses.',
    holding: 'The Supreme Court held that to establish possession of narcotics, the prosecution must prove beyond doubt that the accused had conscious knowledge of the contraband. Mere physical possession without knowledge is insufficient. The court further held that the chain of custody of the recovered substance must be unbroken and the sample sent to the chemical examiner must be the same as recovered. Where the chain is broken, the recovery becomes doubtful.',
    outcome: 'Conviction maintained; sentence reduced to life imprisonment',
    is_landmark: false,
    landmark_reason: null,
    source: 'Manual',
  },
  {
    case_name: 'Ghulam Hussain v The State',
    citation: 'PLD 2007 SC 541',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 2007,
    appellant: 'Ghulam Hussain and others',
    respondent: 'The State',
    judge_names: ['Javed Iqbal J', 'Syed Jamshed Ali J'],
    bench_type: 'Two-Member Bench',
    law_category: 'Criminal',
    law_subcategory: 'Robbery / Dacoity',
    statutes: ['Pakistan Penal Code 1860 s.392-396', 'Criminal Procedure Code 1898', 'Qanun-e-Shahadat Order 1984'],
    keywords: ['dacoity', 'robbery', 'armed robbery', 'identification', 'dock identification', 'TIP', 'test identification parade'],
    headnotes: 'The appellants were convicted of dacoity with murder under Section 396 PPC and sentenced to death. The primary evidence against them was identification by the victim witnesses. The court examined the reliability of dock identification and test identification parade procedures in the context of armed robbery cases where offenders\' faces are often partially concealed.',
    holding: 'The Supreme Court held that dock identification without prior test identification parade (TIP) carries very little evidentiary weight. A TIP must be conducted without delay and under fair conditions. Where the witness has not previously identified the accused in a TIP, dock identification alone is insufficient for conviction. The court set aside the conviction due to the unreliable nature of identification evidence.',
    outcome: 'Conviction set aside; benefit of doubt given',
    is_landmark: false,
    landmark_reason: null,
    source: 'Manual',
  },
  {
    case_name: 'Pakistan v Fazlur Rahman (Anti-Terrorism Jurisdiction)',
    citation: 'PLD 2000 SC 684',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 2000,
    appellant: 'Federation of Pakistan',
    respondent: 'Fazlur Rahman',
    judge_names: ['Irshad Hassan Khan CJ', 'Munir A Sheikh J', 'Rana Bhagwandas J'],
    bench_type: 'Three-Member Bench',
    law_category: 'Anti-Terrorism',
    law_subcategory: 'Definition of Terrorism / ATA Jurisdiction',
    statutes: ['Anti-Terrorism Act 1997 s.6', 'Pakistan Penal Code 1860', 'Criminal Procedure Code 1898'],
    keywords: ['terrorism', 'definition', 'ATA', 'jurisdiction', 'sectarian violence', 'scheduled offenses', 'anti-terrorism court'],
    headnotes: 'This case required the Supreme Court to interpret the definition of "terrorism" under Section 6 of the Anti-Terrorism Act 1997. The question arose as to what type of offenses fall within the jurisdiction of Anti-Terrorism Courts (ATCs) and whether ordinary criminal acts could be tried as terrorism simply because they created fear in the public. The case had significant implications for the scope of ATC jurisdiction nationwide.',
    holding: 'The Supreme Court held that not every criminal act creating terror or fear constitutes terrorism under the ATA. For an act to be terrorism, there must be a design to strike terror in the people or a section thereof, or to adversely affect the religious, sectarian or ethnic feelings of a group. An ordinary murder, even if brutal, is not terrorism unless it has a political, religious, sectarian or ethnic motive. ATCs cannot assume jurisdiction over ordinary criminal cases.',
    outcome: 'ATC jurisdiction clarified; ordinary criminal case remanded to ordinary court',
    is_landmark: true,
    landmark_reason: 'Defined the boundaries of terrorism jurisdiction; prevented misuse of ATC jurisdiction for ordinary crimes; foundational precedent for ATC jurisdiction across Pakistan',
    source: 'Manual',
  },

  // ============================================================
  // FAMILY LAW CASES (5)
  // ============================================================
  {
    case_name: 'Khurshid Bibi v Muhammad Amin',
    citation: 'PLD 1967 SC 97',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 1967,
    appellant: 'Khurshid Bibi',
    respondent: 'Muhammad Amin',
    judge_names: ['A R Cornelius CJ', 'S A Rahman J', 'Hamoodur Rahman J', 'Muhammad Yaqub Ali J'],
    bench_type: 'Full Bench',
    law_category: 'Family',
    law_subcategory: 'Khula / Dissolution of Marriage',
    statutes: ['Dissolution of Muslim Marriages Act 1939', 'West Pakistan Family Courts Act 1964', 'Muslim Personal Law'],
    keywords: ['khula', 'divorce', 'dissolution', 'Muslim marriage', 'consent', 'wife\'s right', 'Islamic law', 'Hanafi fiqh'],
    headnotes: 'This landmark case addressed the right of a Muslim wife to obtain dissolution of marriage through khula (judicial divorce) without the husband\'s consent. The wife sought dissolution of her marriage on grounds of incompatibility and her strong aversion to her husband. The husband refused to divorce her. The case required the Supreme Court to define the scope of khula in Pakistani law and whether courts could grant it without the husband\'s agreement.',
    holding: 'The Supreme Court held that a Muslim wife has an inherent right to obtain dissolution of marriage through khula if she establishes that she cannot live within the limits of Allah with her husband. The court does not require the wife to prove any specific matrimonial fault. The husband\'s consent is not a precondition for khula. Upon the wife returning the mehr (dower), the court may dissolve the marriage. This right cannot be taken away by any custom or agreement.',
    outcome: 'Khula granted; marriage dissolved',
    is_landmark: true,
    landmark_reason: 'Definitively established women\'s right to khula without husband\'s consent in Pakistan; transformative for Muslim women\'s rights; followed by all family courts; most cited family law case',
    source: 'Manual',
  },
  {
    case_name: 'Saima Waheed v The State and others',
    citation: 'PLD 1997 LHC 301',
    citation_type: 'PLD',
    court: 'Lahore High Court',
    court_code: 'LHC',
    year: 1997,
    appellant: 'Saima Waheed',
    respondent: 'The State and Arshad Ahmad (father)',
    judge_names: ['Malik Muhammad Qayyum J', 'Nasira Iqbal J'],
    bench_type: 'Division Bench',
    law_category: 'Family',
    law_subcategory: 'Marriage / Wali / Woman\'s Right to Marry',
    statutes: ['Muslim Personal Law', 'Constitution of Pakistan 1973 Art 35', 'West Pakistan Family Courts Act 1964'],
    keywords: ['marriage', 'wali', 'guardian consent', 'adult woman', 'nikah', 'habeas corpus', 'right to marry', 'forced marriage'],
    headnotes: 'Saima Waheed, an adult Muslim woman, contracted a nikah with Arshad Ahmad of her own free will. Her parents challenged the marriage and sought her recovery through a habeas corpus petition. The key question was whether an adult Muslim woman in Pakistan has the legal capacity to contract her own marriage without the consent of her wali (marriage guardian), and whether such a marriage is valid.',
    holding: 'The majority held that an adult Muslim woman who is of sound mind has the full legal capacity to contract her own marriage without the consent of her wali. The requirement of wali consent for an adult woman is not an absolute requirement in Hanafi jurisprudence which is applicable in Pakistan. A validly contracted nikah by an adult woman is legally binding. The habeas corpus petition was dismissed.',
    outcome: 'Habeas corpus dismissed; marriage upheld',
    is_landmark: true,
    landmark_reason: 'Affirmed adult women\'s right to self-contracted marriage; influential in preventing forced marriages and honor killings; debated extensively in Pakistani legal circles',
    source: 'Manual',
  },
  {
    case_name: 'Imtiaz v Rubina (Child Custody — Welfare Principle)',
    citation: 'PLD 2004 LHC 227',
    citation_type: 'PLD',
    court: 'Lahore High Court',
    court_code: 'LHC',
    year: 2004,
    appellant: 'Imtiaz Ahmad',
    respondent: 'Rubina Perveen',
    judge_names: ['Khalil-ur-Rahman Ramday J'],
    bench_type: 'Single Bench',
    law_category: 'Family',
    law_subcategory: 'Child Custody / Guardianship',
    statutes: ['Guardian and Wards Act 1890', 'West Pakistan Family Courts Act 1964', 'Muslim Personal Law (Hizanat)'],
    keywords: ['child custody', 'guardian', 'welfare of child', 'hizanat', 'mother\'s right', 'father\'s right', 'age of custody'],
    headnotes: 'A divorced couple contested custody of their minor children. The father argued that under Hanafi jurisprudence his right of guardianship (wilayat) was superior. The mother argued she had the right of custody (hizanat) during the children\'s tender years. The court was required to balance Islamic personal law on custody with the statutory welfare principle under the Guardian and Wards Act 1890.',
    holding: 'The court held that the paramount consideration in all custody matters is the welfare of the child, which overrides technical rules of personal law. While Islamic law recognizes the mother\'s right of hizanat during tender years and the father\'s right of wilayat, both must yield to the welfare principle. Courts must consider the child\'s physical, emotional, educational, and moral welfare. Neither parent has an absolute right to custody.',
    outcome: 'Custody awarded based on welfare principle; mother granted custody of minor children',
    is_landmark: false,
    landmark_reason: null,
    source: 'Manual',
  },
  {
    case_name: 'Rashida Begum v Shahab Din (Maintenance)',
    citation: 'PLD 1960 WP 1548',
    citation_type: 'PLD',
    court: 'Lahore High Court',
    court_code: 'LHC',
    year: 1960,
    appellant: 'Rashida Begum',
    respondent: 'Shahab Din',
    judge_names: ['B Z Kaikaus J'],
    bench_type: 'Single Bench',
    law_category: 'Family',
    law_subcategory: 'Maintenance / Nafaqa',
    statutes: ['West Pakistan Family Courts Act 1964', 'Muslim Family Laws Ordinance 1961', 'Muslim Personal Law'],
    keywords: ['maintenance', 'nafaqa', 'wife', 'divorce', 'iddat', 'financial support', 'Muslim family law'],
    headnotes: 'A divorced woman sought maintenance from her former husband for herself and her minor children. The husband argued that maintenance obligation ended upon divorce. The court examined the extent of the husband\'s obligation to pay maintenance during the iddat period, post-iddat maintenance for children, and whether the wife could claim maintenance beyond the iddat period in special circumstances.',
    holding: 'The court held that a husband is obligated to pay maintenance to his divorced wife during the period of iddat. For minor children, the father\'s maintenance obligation continues until the son is able to support himself and the daughter is married. The court has power under the Family Courts Act to award maintenance as it deems fit. Maintenance is a legal right and the court should not place an unreasonable burden on the wife to prove financial need.',
    outcome: 'Maintenance granted to wife and children',
    is_landmark: false,
    landmark_reason: null,
    source: 'Manual',
  },
  {
    case_name: 'Naseem Akhtar v Muhammad Yousaf (Daughters\' Inheritance)',
    citation: 'PLD 2005 SC 298',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 2005,
    appellant: 'Naseem Akhtar and others',
    respondent: 'Muhammad Yousaf and others',
    judge_names: ['Iftikhar Muhammad Chaudhry J', 'Javed Iqbal J'],
    bench_type: 'Two-Member Bench',
    law_category: 'Family',
    law_subcategory: 'Inheritance / Muslim Succession',
    statutes: ['West Pakistan Muslim Personal Law (Shariat) Application Act 1962', 'Constitution of Pakistan 1973 Art 23', 'Muslim Personal Law (Faraid)'],
    keywords: ['inheritance', 'daughters', 'faraid', 'Islamic law', 'succession', 'property', 'deprivation', 'customary law'],
    headnotes: 'Female heirs challenged the exclusion of daughters from agricultural land inheritance on the basis of custom. Male family members argued that local tribal custom excluded daughters from inheriting agricultural land. The court was required to determine whether customary practices could override Islamic law of inheritance (faraid) in Pakistan, and whether daughters could be deprived of their Quranic share in the deceased\'s estate.',
    holding: 'The Supreme Court held that Islamic law of inheritance (faraid) is the applicable law for Muslims in Pakistan and no custom can override a Quranic right of inheritance. Daughters are entitled to their defined share (half of a son\'s share) in the deceased\'s estate. Any custom that excludes daughters from inheritance is void as being repugnant to the Quran and Sunnah. Courts are duty-bound to enforce the Quranic law of inheritance.',
    outcome: 'Daughters\' inheritance rights upheld; custom void',
    is_landmark: true,
    landmark_reason: 'Strongly affirmed daughters\' inheritance rights against custom; significant for rural women\'s property rights; frequently cited in inheritance disputes across Pakistan',
    source: 'Manual',
  },

  // ============================================================
  // PROPERTY CASES (3)
  // ============================================================
  {
    case_name: 'Mst. Zainab Bibi v Abdul Khaliq (Pre-emption)',
    citation: 'PLD 1985 SC 264',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 1985,
    appellant: 'Mst. Zainab Bibi',
    respondent: 'Abdul Khaliq and others',
    judge_names: ['Muhammad Haleem CJ', 'Shafiur Rahman J', 'Pir Muhammad Karam Shah J'],
    bench_type: 'Three-Member Bench',
    law_category: 'Property',
    law_subcategory: 'Pre-emption Rights',
    statutes: ['Punjab Pre-emption Act 1913', 'Transfer of Property Act 1882', 'West Pakistan Muslim Personal Law 1962'],
    keywords: ['pre-emption', 'shuf\'a', 'right of first refusal', 'co-sharers', 'land', 'property transfer', 'Punjab'],
    headnotes: 'A co-sharer in agricultural land sought to exercise the right of pre-emption (shuf\'a) to purchase land sold by another co-sharer to a third party. The question arose regarding the procedural requirements for exercising pre-emption rights and whether the right had been properly and timely exercised. The case examined the nature of pre-emption rights under both statutory law and Islamic law.',
    holding: 'The Supreme Court held that the right of pre-emption is a recognized legal right under both statutory and Islamic law. The right must be exercised promptly upon learning of the sale. The procedure requires: first, the talb-i-muwathabat (immediate demand); second, talb-i-ishhad (demand before witnesses); and third, talb-i-khusumat (legal demand through court). Failure to comply with any step extinguishes the right.',
    outcome: 'Pre-emption suit dismissed for procedural non-compliance',
    is_landmark: false,
    landmark_reason: null,
    source: 'Manual',
  },
  {
    case_name: 'Habib Bank v Gulzar Ahmed (Adverse Possession)',
    citation: 'PLD 1993 LHC 445',
    citation_type: 'PLD',
    court: 'Lahore High Court',
    court_code: 'LHC',
    year: 1993,
    appellant: 'Habib Bank Limited',
    respondent: 'Gulzar Ahmed and others',
    judge_names: ['Irshad Hassan Khan J'],
    bench_type: 'Single Bench',
    law_category: 'Property',
    law_subcategory: 'Adverse Possession / Limitation',
    statutes: ['Limitation Act 1908', 'Transfer of Property Act 1882', 'Specific Relief Act 1877'],
    keywords: ['adverse possession', 'limitation', 'title', 'possession', 'twelve years', 'ouster', 'hostile possession'],
    headnotes: 'The defendant claimed title to commercial property by adverse possession, arguing continuous, open, and hostile possession for more than twelve years. The plaintiff bank claimed ownership through a registered title deed. The court examined the elements required to establish adverse possession under Pakistani law and whether such possession could extinguish a registered title.',
    holding: 'The court held that to succeed in adverse possession, the claimant must prove: (1) actual possession; (2) open and visible possession; (3) exclusive possession; (4) hostile possession adverse to the true owner; (5) continuous possession for the statutory period of 12 years. The possession must be with the clear intention to exclude the true owner. Permissive possession, however long, cannot ripen into title by adverse possession.',
    outcome: 'Adverse possession claim rejected; plaintiff\'s title upheld',
    is_landmark: false,
    landmark_reason: null,
    source: 'Manual',
  },
  {
    case_name: 'Mst. Hawa Bibi v Ghulam Muhammad (Female Property Rights)',
    citation: 'PLD 2015 SC 622',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 2015,
    appellant: 'Mst. Hawa Bibi',
    respondent: 'Ghulam Muhammad and others',
    judge_names: ['Iftikhar Muhammad Chaudhry CJ', 'Jawwad S Khawaja J', 'Sh. Azmat Saeed J'],
    bench_type: 'Three-Member Bench',
    law_category: 'Property',
    law_subcategory: 'Women\'s Property Rights / Gift Deed',
    statutes: ['Transfer of Property Act 1882 s.122-129', 'West Pakistan Muslim Personal Law 1962', 'Constitution Art 23 & 24'],
    keywords: ['women property', 'gift deed', 'hibah', 'undue influence', 'dispossession', 'constitutional right to property', 'women rights'],
    headnotes: 'A widow sought cancellation of a gift deed executed in favor of her son, alleging it was obtained through undue influence and that she was unaware of its contents. She had been dispossessed of her home as a result. The case raised important issues about the vulnerability of illiterate women to undue influence in property transactions and the protection afforded by courts.',
    holding: 'The Supreme Court held that courts must be vigilant in protecting women from undue influence in property transactions. Where a woman is illiterate, elderly, or in a position of dependence, the burden shifts to the beneficiary to prove the transaction was freely entered into with full understanding. Mere execution of documents is insufficient without proof of informed consent. The gift deed was set aside.',
    outcome: 'Gift deed cancelled; property restored to widow',
    is_landmark: false,
    landmark_reason: null,
    source: 'Manual',
  },

  // ============================================================
  // ISLAMIC/SHARIAT CASES (2)
  // ============================================================
  {
    case_name: 'Mahmood-ur-Rehman Faisal v Secretary Ministry of Law (Riba Case)',
    citation: 'PLD 1992 FSC 1',
    citation_type: 'PLD',
    court: 'Federal Shariat Court',
    court_code: 'FSC',
    year: 1992,
    appellant: 'Mahmood-ur-Rehman Faisal',
    respondent: 'Secretary, Ministry of Law and Justice',
    judge_names: ['Tanzil-ur-Rahman CJ (FSC)', 'Abdul Karim Khan Kundi J', 'Fida Muhammad Khan J'],
    bench_type: 'Full Bench (FSC)',
    law_category: 'Islamic/Shariat',
    law_subcategory: 'Riba / Banking Interest',
    statutes: ['Banking Companies Ordinance 1962', 'Money Lenders Ordinance', 'Constitution of Pakistan 1973 Art 227-229'],
    keywords: ['riba', 'interest', 'banking', 'Islamic finance', 'Federal Shariat Court', 'repugnancy', 'Quran', 'Sunnah'],
    headnotes: 'The petitioner challenged the entire interest-based banking system in Pakistan as repugnant to the injunctions of Islam under Article 227 of the Constitution. The Federal Shariat Court was petitioned to declare all laws permitting the charging of interest (riba) in banking transactions as un-Islamic. This was a comprehensive challenge to the conventional banking system from an Islamic law perspective.',
    holding: 'The Federal Shariat Court held that riba (interest) is prohibited under Islamic law and all forms of interest — whether simple or compound, on commercial or personal loans — are covered by this prohibition. The court declared all laws permitting bank interest as repugnant to the Quran and Sunnah. The government was directed to convert the banking system to an interest-free system. The Shariat Appellate Bench of the Supreme Court later stayed this judgment pending appeal.',
    outcome: 'Interest-based banking laws declared un-Islamic; implementation stayed pending appeal',
    is_landmark: true,
    landmark_reason: 'Most significant FSC ruling on Islamic economics; challenged entire banking system; triggered extensive debate on Islamic finance; case remained in litigation for decades affecting banking sector',
    source: 'Manual',
  },
  {
    case_name: 'Hazoor Bakhsh v Federation of Pakistan (Hudood)',
    citation: 'PLD 1981 FSC 145',
    citation_type: 'PLD',
    court: 'Federal Shariat Court',
    court_code: 'FSC',
    year: 1981,
    appellant: 'Hazoor Bakhsh',
    respondent: 'Federation of Pakistan',
    judge_names: ['Aftab Hussain J (FSC)', 'Muhammad Taqi Usmani J', 'Noor ul Haq J'],
    bench_type: 'Full Bench (FSC)',
    law_category: 'Islamic/Shariat',
    law_subcategory: 'Hudood / Hadd Punishment',
    statutes: ['Offence of Zina (Enforcement of Hudood) Ordinance 1979', 'Offences Against Property (Enforcement of Hudood) Ordinance 1979', 'Constitution Art 227'],
    keywords: ['hudood', 'hadd', 'Islamic punishments', 'zina', 'qazf', 'theft', 'Islamic law', 'evidence requirements'],
    headnotes: 'This case examined the evidentiary standards required to impose hadd punishments under the Hudood Ordinances. The court was required to determine the strict proof requirements under Islamic law for imposing Quranic punishments such as amputation for theft and flogging for zina. The case raised the standard of proof for hadd as distinct from tazir (discretionary) punishments.',
    holding: 'The Federal Shariat Court held that the standard of proof for hadd punishments is extremely high — either confession or the testimony of the required number of witnesses of specified character. For zina hadd, four male Muslim witnesses of good character who actually witnessed the act are required. For theft hadd, the property must be above the nisab value and taken from a secure place. In the absence of this standard, the court may impose tazir punishment.',
    outcome: 'Hadd conviction set aside; tazir punishment substituted',
    is_landmark: true,
    landmark_reason: 'Established strict evidentiary requirements for hadd punishments; significant for Islamic criminal law in Pakistan; practically made hadd punishments nearly impossible to impose',
    source: 'Manual',
  },

  // ============================================================
  // COMMERCIAL/BANKING CASES (3)
  // ============================================================
  {
    case_name: 'Muslim Commercial Bank v State Cement Corporation (Contract Frustration)',
    citation: 'PLD 1995 SC 784',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 1995,
    appellant: 'Muslim Commercial Bank Ltd',
    respondent: 'State Cement Corporation of Pakistan',
    judge_names: ['Sajjad Ali Shah CJ', 'Fazal Ilahi Khan J', 'Saleem Akhtar J'],
    bench_type: 'Three-Member Bench',
    law_category: 'Commercial',
    law_subcategory: 'Contract Law / Frustration',
    statutes: ['Contract Act 1872 s.56', 'Sale of Goods Act 1930', 'Specific Relief Act 1877'],
    keywords: ['contract', 'frustration', 'force majeure', 'impossibility', 'supervening impossibility', 'discharge', 'Section 56 Contract Act'],
    headnotes: 'A commercial contract was entered into for the supply of cement. Subsequent government price controls and restrictions made performance of the contract commercially impractical and contrary to government regulations. The question arose whether the contract had been frustrated by the supervening governmental action, discharging both parties from further performance. The court examined the doctrine of frustration under Section 56 of the Contract Act 1872.',
    holding: 'The Supreme Court held that a contract becomes void under Section 56 of the Contract Act 1872 when performance becomes impossible due to a supervening event not foreseeable at the time of contracting. Government regulations that make contractual performance illegal or impossible are a classic ground of frustration. The party seeking to invoke frustration must show the event was not self-induced and was not a foreseeable risk. Upon frustration, both parties are discharged from future obligations.',
    outcome: 'Contract declared frustrated; parties discharged',
    is_landmark: false,
    landmark_reason: null,
    source: 'Manual',
  },
  {
    case_name: 'National Bank of Pakistan v Yakoob & Sons (Bank Guarantee)',
    citation: 'PLD 2001 SC 116',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 2001,
    appellant: 'National Bank of Pakistan',
    respondent: 'Yakoob & Sons',
    judge_names: ['Irshad Hassan Khan CJ', 'Rana Bhagwandas J', 'Ch. Muhammad Arif J'],
    bench_type: 'Three-Member Bench',
    law_category: 'Banking',
    law_subcategory: 'Bank Guarantee / Letter of Credit',
    statutes: ['Contract Act 1872 s.126-129', 'Banking Companies Ordinance 1962', 'Negotiable Instruments Act 1881'],
    keywords: ['bank guarantee', 'letter of credit', 'surety', 'performance bond', 'demand guarantee', 'fraud exception', 'autonomy principle'],
    headnotes: 'A bank was called upon to make payment under a performance guarantee issued in favor of a foreign buyer. The account holder sought an injunction preventing the bank from making payment, alleging fraud by the beneficiary. The court examined the nature of bank guarantees as autonomous undertakings and the narrow fraud exception to the autonomy principle.',
    holding: 'The Supreme Court held that a bank guarantee is an autonomous undertaking independent of the underlying contract. The bank\'s obligation is to pay upon demand if the conditions of the guarantee are met, regardless of disputes between the account holder and beneficiary. The court will not normally restrain payment under a bank guarantee. The only exception is clear and established fraud brought to the bank\'s notice before payment. Mere allegations of fraud are insufficient.',
    outcome: 'Injunction refused; bank entitled to pay guarantee',
    is_landmark: false,
    landmark_reason: null,
    source: 'Manual',
  },
  {
    case_name: 'SECP v Tri-Star Petroleum (Company Law)',
    citation: 'PLD 2012 SC 440',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 2012,
    appellant: 'Securities and Exchange Commission of Pakistan',
    respondent: 'Tri-Star Petroleum Company Ltd',
    judge_names: ['Iftikhar Muhammad Chaudhry CJ', 'Gulzar Ahmed J', 'Sh. Azmat Saeed J'],
    bench_type: 'Three-Member Bench',
    law_category: 'Commercial',
    law_subcategory: 'Company Law / Corporate Governance',
    statutes: ['Companies Ordinance 1984 (now Companies Act 2017)', 'Securities and Exchange Commission of Pakistan Act 1997', 'Listing Regulations'],
    keywords: ['company law', 'SECP', 'corporate governance', 'directors', 'fiduciary duty', 'minority shareholders', 'winding up'],
    headnotes: 'The Securities and Exchange Commission sought to wind up a listed company on grounds of mismanagement, oppression of minority shareholders, and failure to comply with regulatory requirements. The case raised important questions about SECP\'s regulatory powers, the rights of minority shareholders, and the standard for winding up a company on just and equitable grounds.',
    holding: 'The Supreme Court held that SECP has broad powers to regulate companies in the public interest and can petition for winding up where there is gross mismanagement or oppression. Directors owe fiduciary duties to the company and all shareholders, not just the majority. Oppression of minority shareholders contrary to fair dealing justifies court intervention. The just and equitable ground for winding up applies where the company\'s substratum has failed or there is a breakdown in mutual trust.',
    outcome: 'SECP petition for investigation allowed; directors held liable',
    is_landmark: false,
    landmark_reason: null,
    source: 'Manual',
  },

  // ============================================================
  // HUMAN RIGHTS CASES (2)
  // ============================================================
  {
    case_name: 'Shehla Zia v WAPDA',
    citation: 'PLD 1994 SC 693',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 1994,
    appellant: 'Shehla Zia and others',
    respondent: 'WAPDA (Water and Power Development Authority)',
    judge_names: ['Nasim Hassan Shah CJ', 'Sajjad Ali Shah J', 'Saleem Akhtar J'],
    bench_type: 'Three-Member Bench',
    law_category: 'Human Rights',
    law_subcategory: 'Environmental Rights / Right to Life',
    statutes: ['Constitution of Pakistan 1973 Art 9', 'Constitution Art 14', 'Environmental Protection Ordinance 1983'],
    keywords: ['environmental rights', 'right to life', 'Article 9', 'electromagnetic radiation', 'WAPDA', 'grid station', 'precautionary principle', 'human rights'],
    headnotes: 'Residents of a Lahore housing society challenged WAPDA\'s installation of a high voltage transmission line and grid station near their homes, alleging it posed health hazards through electromagnetic radiation. The petitioners invoked their fundamental right to life under Article 9 of the Constitution. The case expanded the definition of "life" in Article 9 to include the right to a clean and healthy environment.',
    holding: 'The Supreme Court held that the right to life under Article 9 includes the right to live in a clean, healthy, and safe environment. The state has a duty to protect citizens from environmental hazards. Where there is scientific uncertainty about the harm from a proposed activity, the precautionary principle applies — the burden falls on the proponent to show no harm, not on citizens to prove harm. WAPDA was directed to relocate the grid station.',
    outcome: 'WAPDA directed to relocate grid station; precautionary principle applied',
    is_landmark: true,
    landmark_reason: 'First major environmental rights case in Pakistan; expanded Article 9 right to life to include environmental rights; introduced precautionary principle; foundational for environmental litigation in Pakistan',
    source: 'Manual',
  },
  {
    case_name: 'Adiala Jail Case — Missing Persons / Enforced Disappearances',
    citation: 'PLD 2014 SC 699',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 2014,
    appellant: 'Human Rights Case (Suo Motu)',
    respondent: 'Federation of Pakistan and Intelligence Agencies',
    judge_names: ['Iftikhar Muhammad Chaudhry CJ', 'Jawwad S Khawaja J', 'Sh. Azmat Saeed J'],
    bench_type: 'Three-Member Bench',
    law_category: 'Human Rights',
    law_subcategory: 'Enforced Disappearances / Habeas Corpus',
    statutes: ['Constitution of Pakistan 1973 Art 9 & 10', 'Constitution Art 184(3)', 'Criminal Procedure Code 1898'],
    keywords: ['enforced disappearances', 'missing persons', 'habeas corpus', 'intelligence agencies', 'ISI', 'MI', 'fundamental rights', 'Article 9', 'suo motu'],
    headnotes: 'The Supreme Court took suo motu notice of the rampant phenomenon of enforced disappearances in Pakistan, particularly in Balochistan and the tribal belt. Hundreds of families appeared before the court alleging their relatives had been picked up by intelligence agencies without any legal process. The court was confronted with systemic denial of the right to liberty and the right to a fair trial guaranteed under Articles 9 and 10 of the Constitution.',
    holding: 'The Supreme Court held that enforced disappearances constitute a grave violation of fundamental rights under Articles 9 and 10 of the Constitution. Intelligence agencies cannot detain any person without legal authority. The state must account for all persons reported missing. The court directed the establishment of a Commission of Inquiry on Enforced Disappearances and ordered agencies to produce or account for missing persons. Compensation was ordered to families of the disappeared.',
    outcome: 'Landmark directions issued; Commission on Enforced Disappearances established',
    is_landmark: true,
    landmark_reason: 'Supreme Court actively confronted enforced disappearances at a systemic level; established accountability of intelligence agencies; led to establishment of the Commission on Enforced Disappearances; regularly cited in human rights litigation',
    source: 'Manual',
  },

  // ============================================================
  // NAB/ACCOUNTABILITY (1)
  // ============================================================
  {
    case_name: 'NAB v Syed Mustufa Kazmi (Assets Beyond Means)',
    citation: 'PLD 2009 SC 172',
    citation_type: 'PLD',
    court: 'Supreme Court of Pakistan',
    court_code: 'SC',
    year: 2009,
    appellant: 'National Accountability Bureau',
    respondent: 'Syed Mustufa Kazmi',
    judge_names: ['Iftikhar Muhammad Chaudhry CJ', 'Raja Fayyaz Ahmad J', 'Javed Iqbal J'],
    bench_type: 'Three-Member Bench',
    law_category: 'NAB/Accountability',
    law_subcategory: 'Corruption / Assets Beyond Means',
    statutes: ['National Accountability Bureau Ordinance 1999 s.9', 'Anti-Corruption Establishment Act', 'Prevention of Corruption Act 1947'],
    keywords: ['NAB', 'corruption', 'assets beyond means', 'accountability', 'plea bargain', 'reverse burden of proof', 'public office holder'],
    headnotes: 'A senior government official was prosecuted by NAB for possessing assets disproportionate to his known sources of income. The accused challenged the reverse burden of proof under the NAB Ordinance 1999, whereby a public officeholder must explain all assets. The case examined the constitutionality of presumption of guilt in accountability cases and the burden of proof in corruption prosecutions.',
    holding: 'The Supreme Court upheld the reverse burden of proof in NAB cases involving assets beyond means, holding that it is constitutionally permissible given the public interest in eradicating corruption. A public officeholder who possesses assets disproportionate to income must satisfactorily account for them. The burden then shifts to the accused to explain the source of wealth. Failure to provide a satisfactory explanation supports conviction. This does not violate the presumption of innocence when the initial burden on prosecution is met.',
    outcome: 'Reverse burden of proof upheld; conviction maintained',
    is_landmark: false,
    landmark_reason: null,
    source: 'Manual',
  },

  // ============================================================
  // CYBER CRIME (1)
  // ============================================================
  {
    case_name: 'Zainab Abbas v Federation of Pakistan (PECA Challenge)',
    citation: 'PLD 2021 LHC 550',
    citation_type: 'PLD',
    court: 'Lahore High Court',
    court_code: 'LHC',
    year: 2021,
    appellant: 'Zainab Abbas and others (Journalists/Civil Society)',
    respondent: 'Federation of Pakistan and others',
    judge_names: ['Ali Baqar Najafi J', 'Sardar Ahmad Naeem J'],
    bench_type: 'Division Bench',
    law_category: 'Cyber Crime',
    law_subcategory: 'Freedom of Expression / PECA / Online Speech',
    statutes: ['Prevention of Electronic Crimes Act 2016 s.20', 'Constitution of Pakistan 1973 Art 19 & 19-A', 'Pakistan Penal Code s.499-500'],
    keywords: ['PECA', 'cyber crime', 'online defamation', 'freedom of expression', 'Article 19', 'digital rights', 'social media', 'Section 20 PECA'],
    headnotes: 'Journalists and civil society organizations challenged Section 20 of the Prevention of Electronic Crimes Act 2016, which criminalizes online defamation, as an unconstitutional restriction on freedom of expression under Article 19. The petitioners argued the provision was overbroad, vague, and was being misused to target journalists and critics of the government. The case raised the fundamental tension between protecting reputation online and protecting free speech.',
    holding: 'The Lahore High Court held that Section 20 of PECA must be read narrowly and in conformity with Article 19 of the Constitution. Criminal liability for online speech must meet the constitutional standard — such restrictions must be reasonable and in the interest of the glory of Islam, public order, decency, or morality. The court held that online criticism of public figures on matters of public interest is protected. The provision should not be used to silence legitimate dissent or journalism.',
    outcome: 'Constitutional challenge partially upheld; Section 20 given restrictive interpretation',
    is_landmark: true,
    landmark_reason: 'First major constitutional challenge to PECA; defined boundaries of online free speech; significant for digital rights and journalism in Pakistan; widely cited in PECA prosecutions',
    source: 'Manual',
  },
]

async function main() {
  console.log(`Seeding ${precedents.length} Pakistani legal precedents...`)

  const { data, error } = await supabase
    .from('precedents')
    .insert(precedents)
    .select('id, case_name')

  if (error) {
    console.error('Error seeding precedents:', error)
    process.exit(1)
  }

  console.log(`Successfully seeded ${data?.length} precedents:`)
  data?.forEach((p, i) => {
    console.log(`  ${i + 1}. ${p.case_name} (${p.id})`)
  })

  console.log('\nSeed complete!')
}

main()
