import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import toast from 'react-hot-toast';

export default function AnalysisResult({ result, module, loading }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(result);
    setCopied(true);
    toast.success('Copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const filename = `${module.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.txt`;
    const blob = new Blob([`${module}\nGenerated by AnalystAI on ${new Date().toLocaleString()}\n${'='.repeat(60)}\n\n${result}`], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded');
  };

  const handlePrint = () => {
    const date = new Date().toLocaleString();
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${module} — AnalystAI Report</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: 'Georgia', serif; color: #111; background: white; padding: 40px 60px; max-width: 860px; margin: 0 auto; }
          .header { border-bottom: 3px solid #0d1117; padding-bottom: 16px; margin-bottom: 24px; }
          .logo { font-size: 22px; font-weight: 900; color: #1a1a2e; letter-spacing: -1px; }
          .logo span { color: #2563eb; }
          .report-title { font-size: 20px; font-weight: 700; margin-top: 10px; color: #0d1117; }
          .meta { font-size: 12px; color: #666; margin-top: 4px; }
          .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 11px; color: #999; }
          h1 { font-size: 22px; margin: 28px 0 10px; color: #0d1117; }
          h2 { font-size: 18px; margin: 24px 0 8px; color: #1a1a2e; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
          h3 { font-size: 15px; margin: 18px 0 6px; color: #374151; }
          p { line-height: 1.7; margin-bottom: 10px; font-size: 13.5px; }
          ul, ol { margin: 8px 0 12px 20px; }
          li { line-height: 1.7; font-size: 13.5px; margin-bottom: 4px; }
          strong { color: #0d1117; }
          table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 12.5px; }
          th { background: #f1f5f9; padding: 8px 12px; text-align: left; font-weight: 700; border: 1px solid #ddd; }
          td { padding: 7px 12px; border: 1px solid #e5e7eb; vertical-align: top; }
          tr:nth-child(even) td { background: #fafafa; }
          code { background: #f3f4f6; padding: 1px 5px; border-radius: 3px; font-size: 12px; }
          pre { background: #f3f4f6; padding: 12px; border-radius: 6px; overflow-x: auto; font-size: 12px; margin: 12px 0; }
          blockquote { border-left: 3px solid #2563eb; padding: 8px 16px; margin: 12px 0; background: #eff6ff; font-style: italic; }
          @media print {
            body { padding: 20px 30px; }
            .no-print { display: none !important; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">Analyst<span>AI</span></div>
          <div class="report-title">${module}</div>
          <div class="meta">Generated on ${date} &nbsp;|&nbsp; analystai.com &nbsp;|&nbsp; Powered by Claude AI</div>
        </div>
        <div id="content"></div>
        <div class="footer">
          This report is generated by AnalystAI for educational and research purposes only. Not financial advice. Always consult a licensed financial advisor before making investment decisions.
        </div>
      </body>
      </html>
    `);
    printWindow.document.close();

    // Use marked if available, else do basic conversion
    const contentDiv = printWindow.document.getElementById('content');
    // Convert markdown to basic HTML for printing
    const html = result
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/`(.+?)`/g, '<code>$1</code>')
      .replace(/^\- (.+)$/gm, '<li>$1</li>')
      .replace(/^\d+\. (.+)$/gm, '<li>$1</li>')
      .replace(/(<li>.*<\/li>)/gs, '<ul>$1</ul>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/^(?!<[hul])/gm, '')
      .trim();
    contentDiv.innerHTML = `<p>${html}</p>`;

    setTimeout(() => {
      printWindow.print();
    }, 400);

    toast.success('Print dialog opened');
  };

  if (loading) {
    return (
      <div className="result-container">
        <div className="loading-box">
          <div className="loading-spinner"></div>
          <div className="loading-text">Generating institutional analysis...</div>
          <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>This may take 15–30 seconds</div>
        </div>
      </div>
    );
  }

  if (!result) return null;

  return (
    <div className="result-container">
      <div className="result-header">
        <div className="result-title">
          <span style={{ color: 'var(--accent-green)' }}>✓</span>
          {module} — Analysis Complete
        </div>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>Saved to history</span>
          <button className="btn-copy" onClick={handlePrint} title="Export as PDF / Print">
            ⎙ Export PDF
          </button>
          <button className="btn-copy" onClick={handleDownload}>
            ↓ Download
          </button>
          <button className="btn-copy" onClick={handleCopy}>
            {copied ? '✓ Copied' : '⎘ Copy'}
          </button>
        </div>
      </div>
      <div className="result-body markdown-body">
        <ReactMarkdown>{result}</ReactMarkdown>
      </div>
    </div>
  );
}
